"""MCP tools for PerformanceAnalyst agent."""

import json
from datetime import datetime, timezone


def generate_performance_report(metrics_json: str, period: str) -> dict:
    """Generate a structured performance report from affiliate metrics data.

    Parses the provided metrics JSON and returns a comprehensive report
    with KPI analysis, benchmarks, and optimization areas.

    Args:
        metrics_json: JSON string containing affiliate performance metrics.
            Expected fields per affiliate/campaign: clicks, impressions,
            conversions, revenue, cost, affiliate_name, etc.
        period: The reporting period (e.g., "last 30 days", "Q1 2025",
            "2025-01-01 to 2025-03-31").

    Returns:
        A structured report dictionary with metrics analysis and recommendations.
    """
    # Parse metrics JSON with error handling
    try:
        metrics = json.loads(metrics_json)
    except json.JSONDecodeError as e:
        return {
            "error": f"Invalid JSON in metrics_json: {str(e)}",
            "hint": "Ensure metrics_json is a valid JSON string. Expected a list of "
                    "objects or a single object with affiliate performance data.",
        }
    except TypeError as e:
        return {
            "error": f"Invalid input type for metrics_json: {str(e)}",
            "hint": "metrics_json must be a JSON-encoded string.",
        }

    # Normalize to list
    if isinstance(metrics, dict):
        metrics = [metrics]

    if not isinstance(metrics, list):
        return {
            "error": "metrics_json must decode to a JSON object or array of objects.",
            "hint": "Provide either a single metrics object or a list of metrics objects.",
        }

    # Build the report
    report = {
        "report_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "period": period,
        "metrics": metrics,
        "analysis_framework": {
            "kpis": [
                "CTR (Click-Through Rate)",
                "Conversion Rate",
                "EPC (Earnings Per Click)",
                "RPM (Revenue Per Mille)",
                "AOV (Average Order Value)",
                "ROI (Return on Investment)",
            ],
            "benchmarks": {
                "good_ctr": "2-5%",
                "good_conversion_rate": "1-3%",
                "good_epc": "$0.50-$2.00",
            },
        },
        "optimization_areas": [
            "Affiliate selection and recruitment",
            "Commission structure optimization",
            "Creative and landing page performance",
            "Traffic quality and source analysis",
            "Conversion funnel optimization",
            "Seasonal and trend-based adjustments",
        ],
        "instructions": (
            "Analyze the provided metrics against the benchmarks in the analysis "
            "framework. For each affiliate or campaign in the data, calculate CTR, "
            "conversion rate, EPC, and ROI. Identify top performers and "
            "underperformers. Provide specific, data-backed recommendations for "
            "each optimization area that is relevant. Rank recommendations by "
            "expected revenue impact."
        ),
    }

    return report


def calculate_affiliate_roi(
    total_cost: float,
    total_revenue: float,
    time_period_days: int,
) -> dict:
    """Calculate ROI and financial projections for affiliate campaigns.

    Computes profitability metrics including ROI percentage, daily and monthly
    projections, and break-even analysis.

    Args:
        total_cost: Total cost/spend for the affiliate campaign(s) in the period.
        total_revenue: Total revenue generated by the affiliate campaign(s) in the period.
        time_period_days: Number of days in the measurement period.

    Returns:
        A dictionary with ROI analysis, projections, and assessment.
    """
    if time_period_days <= 0:
        return {
            "error": "time_period_days must be a positive integer.",
        }

    profit = total_revenue - total_cost
    roi_percentage = ((profit / total_cost) * 100) if total_cost != 0 else 0.0

    daily_revenue = total_revenue / time_period_days
    daily_profit = profit / time_period_days

    monthly_projected_revenue = daily_revenue * 30
    monthly_projected_profit = daily_profit * 30

    # Break-even analysis
    if total_revenue <= 0:
        break_even_days = None  # Cannot break even with zero revenue
    elif daily_profit <= 0:
        break_even_days = None  # Not profitable, cannot break even
    else:
        break_even_days = round(total_cost / daily_profit)

    # Assessment
    if profit > 0:
        assessment = "profitable"
    elif profit == 0:
        assessment = "break-even"
    else:
        assessment = "unprofitable"

    return {
        "total_cost": round(total_cost, 2),
        "total_revenue": round(total_revenue, 2),
        "profit": round(profit, 2),
        "roi_percentage": round(roi_percentage, 2),
        "time_period_days": time_period_days,
        "daily_revenue": round(daily_revenue, 2),
        "daily_profit": round(daily_profit, 2),
        "monthly_projected_revenue": round(monthly_projected_revenue, 2),
        "monthly_projected_profit": round(monthly_projected_profit, 2),
        "break_even_days": break_even_days,
        "assessment": assessment,
    }
